### ISSUE TITLE
websockets code incomplete here ?

### ISSUE THREAD

**Issue by joeblew99** [dancannon/GoRethink_TodoDemo#10]
this seems to be not using web sockets yet ?
if i open two tabs, they do not keep up to date.

the code is really well structured. Probably the best example i have seen.
i would be happy to finish it, but need a little more advice.

**Comment by dancannon** [comment]
Hey, this should now be working thanks to @frankdugan3.

**Comment by joeblew99** [comment]
Thanks I got it working just fine off Frank's code
