### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by straikongit** [dancannon/GoRethink_TodoDemo#7]
when using the latest GoRethink driver the app runs into io-timeout every time the Timeout limit (set in server.go) is reached.
with v0.6.3 everything works like expected.

**Comment by dancannon** [comment]
Thanks for the bug report, the reason that this stopped working in v0.7 is that timeouts were broken previously.

To prevent the application from crashing I have updated the queries so if an error is returned then it is retried. I have also removed the timeout as when using changefeeds timeouts are not wanted. 

I may look into a better solution for timeouts and changefeeds in the future as this is not the first time I have seen issues.
